version: '3'

services:
    # kafkaserver:
    #   image: spotify/kafka
    #   ports:
    #     - 2181:2181
    #     - 9092:9092
    react-chat-front:
      container_name: react-chat-front
      build:
        context: ./React-front
        dockerfile: Dockerfile
      volumes:
        - './React-front:/app'
        - '/app/node_modules'
      ports:
        - 3001:3000
      environment:
        - CHOKIDAR_USEPOLLING=true